/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mapsii;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.mycompany.mapsii.obj.Enums.CarEnum;
import com.mycompany.mapsii.obj.Preference;

import javax.swing.*;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileWriter;
import java.util.Arrays;
import java.util.Enumeration;
import java.util.Objects;

/**
 * @author Francis
 */
public class Preferences extends javax.swing.JDialog {
    private MapsII parent;
    /**
     * Creates new form Preferences
     */
    public Preferences() {
        parent = new MapsII();
    }

    public Preferences(MapsII m) {
        parent = m;
        initComponents();
        this.setResizable(false);
        initDisplay();
        this.setTitle("Préferences");
    }

    private void initDisplay() {
        String[] def = {""};
        // 1. Generate combo box content
        // 1.1 set combobox measurment
        try {
            cboMeasurment.setModel(new DefaultComboBoxModel<String>(Preference.getOptionsMeasure()));
        } catch (Exception e) {
            cboMeasurment.setModel(new DefaultComboBoxModel<String>(def));
        }

        // 1.2 set combobox background color
        try {
            cboBackground.setModel(new DefaultComboBoxModel<String>(Preference.getOptionsColor()));
        } catch (Exception e) {
            cboBackground.setModel(new DefaultComboBoxModel<String>(def));
        }

        // 1.3 set combobox car type
        String[] carTypes = null;
        try {
            carTypes = Arrays.stream(CarEnum.class.getEnumConstants()).map(Enum::name).toArray(String[]::new);
            cboCarType.setModel(new DefaultComboBoxModel<String>(carTypes));
        } catch (Exception e) {
            cboCarType.setModel(new DefaultComboBoxModel<String>(def));
        }

        // 2. Display selected value
        // 2.1 Select most important variable
        for (Enumeration<AbstractButton> buttons = grpVariables.getElements(); buttons.hasMoreElements(); ) {
            AbstractButton button = buttons.nextElement();
            button.setSelected(Objects.equals(button.getAccessibleContext().getAccessibleName(), Preference.getInstance().variableDominante));
        }

        // 2.2 Select measurment
        try {
            cboMeasurment.setSelectedIndex(Preference.getInstance().mesureDistance);
        } catch (Exception e) {
            cboMeasurment.setSelectedIndex(0);
        }

        // 2.3 Select background color
        try {
            cboBackground.setSelectedIndex(Preference.getInstance().couleurFond);
        } catch (Exception e) {
            cboBackground.setSelectedIndex(0);
        }

        // 2.4 Select car type
        try {
            for (int i = 0; i < Objects.requireNonNull(carTypes).length; i++) {
                if (Objects.equals(carTypes[i], Preference.getInstance().typeVoiture)) {
                    cboCarType.setSelectedIndex(i);
                }
            }
        } catch (Exception e) {
            cboCarType.setSelectedIndex(0);
        }
    }

    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpVariables = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radioDuration = new javax.swing.JRadioButton();
        radioEmission = new javax.swing.JRadioButton();
        radioCost = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboMeasurment = new javax.swing.JComboBox<>();
        cboCarType = new javax.swing.JComboBox<>();
        cboBackground = new javax.swing.JComboBox<>();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setName(""); // NOI18N

        jLabel1.setText("Variable dominante");

        grpVariables.add(radioDuration);
        radioDuration.setText("Durée");
        radioDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDurationActionPerformed(evt);
            }
        });

        grpVariables.add(radioEmission);
        radioEmission.setText("Émission de CO2");

        grpVariables.add(radioCost);
        radioCost.setText("Coût du trajet");

        jLabel2.setText("Mesure de distance");

        jLabel3.setText("Type de voiture");

        jLabel4.setText("Couleur de fond");

        cboMeasurment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboCarType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboBackground.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCancel.setText("Annuler ");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Sauvegarder");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioDuration)
                                    .addComponent(radioEmission)
                                    .addComponent(radioCost, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)))
                                .addComponent(btnSave))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(91, 91, 91)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboCarType, 0, 97, Short.MAX_VALUE)
                                    .addComponent(cboBackground, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cboMeasurment, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioDuration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioEmission)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioCost)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboMeasurment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboCarType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        radioDuration.getAccessibleContext().setAccessibleName("Duration");
        radioEmission.getAccessibleContext().setAccessibleName("Emission");
        radioCost.getAccessibleContext().setAccessibleName("Cost");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDurationActionPerformed

    private void quitDialog(){
        dispose();
        parent.setEnabled(true);
        parent.setVisible(true);
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        quitDialog();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // Save Fields
        savePreferences();

        Gson g = new GsonBuilder().setPrettyPrinting().create();
        try {
            FileWriter writer = new FileWriter(MapsII.pathToHere + "/config.json");
            g.toJson(Preference.getInstance(), writer);
            writer.flush();
            writer.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        quitDialog();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void savePreferences() {
        // Save the most important variable
        for (Enumeration<AbstractButton> buttons = grpVariables.getElements(); buttons.hasMoreElements(); ) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                Preference.getInstance().variableDominante = button.getAccessibleContext().getAccessibleName();
                break;
            }
        }

        // Save the measure
        Preference.getInstance().mesureDistance = cboMeasurment.getSelectedIndex();
        // Save the Car type
        String[] carTypes = Arrays.stream(CarEnum.class.getEnumConstants()).map(Enum::name).toArray(String[]::new);
        Preference.getInstance().typeVoiture = carTypes[cboCarType.getSelectedIndex()];
        // Save the Background color
        Preference.getInstance().couleurFond = cboBackground.getSelectedIndex();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preferences().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cboBackground;
    private javax.swing.JComboBox<String> cboCarType;
    private javax.swing.JComboBox<String> cboMeasurment;
    private javax.swing.ButtonGroup grpVariables;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioCost;
    private javax.swing.JRadioButton radioDuration;
    private javax.swing.JRadioButton radioEmission;
    // End of variables declaration//GEN-END:variables
}
